# Generated by Django 5.1 on 2025-09-28 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenNganh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Machuyennganh', models.IntegerField()),
                ('Tenchuyennganh', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Makhoa', models.IntegerField()),
                ('Tenkhoa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mgv', models.CharField(max_length=50)),
                ('Tengv', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('So_dien_thoai', models.CharField(max_length=50)),
                ('ChuyenNganh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.chuyennganh')),
                ('Khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='DoAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_do_an', models.IntegerField()),
                ('Ten_do_an', models.CharField(max_length=255)),
                ('Mo_ta', models.TextField()),
                ('So_luong_sv_dk', models.IntegerField(blank=True, default=None, null=True)),
                ('GiangVien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.giangvien')),
                ('Khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.khoa')),
            ],
        ),
        migrations.AddField(
            model_name='chuyennganh',
            name='Khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.khoa'),
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Msv', models.CharField(max_length=50)),
                ('Tensv', models.CharField(max_length=50)),
                ('Lop', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('So_dien_thoai', models.CharField(max_length=50)),
                ('ChuyenNganh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.chuyennganh')),
                ('Khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='DangKyDoAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianDangKy', models.DateTimeField(auto_now_add=True, null=True)),
                ('DoAn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.doan')),
                ('SinhVien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.sinhvien')),
            ],
        ),
    ]
