# Generated by Django 5.1 on 2025-10-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLDA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doan',
            name='ChuyenNganh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='QLDA.chuyennganh'),
        ),
    ]
