# Generated by Django 5.1 on 2025-10-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLDA', '0002_doan_chuyennganh'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangkydoan',
            name='File_nop',
            field=models.FileField(blank=True, null=True, upload_to='nop_do_an/'),
        ),
    ]
