# Generated by Django 5.1 on 2025-10-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLDA', '0003_dangkydoan_file_nop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangkydoan',
            name='File_nop',
        ),
        migrations.CreateModel(
            name='FileDoAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files_do_an/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dang_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='QLDA.dangkydoan')),
            ],
        ),
    ]
