# Generated by Django 5.1 on 2025-10-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLDA', '0004_remove_dangkydoan_file_nop_filedoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangkydoan',
            name='file_nop',
            field=models.FileField(blank=True, null=True, upload_to='files_do_an/'),
        ),
        migrations.DeleteModel(
            name='FileDoAn',
        ),
    ]
