# Generated by Django 5.1 on 2025-10-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLDA', '0006_remove_dangkydoan_file_nop_filedoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedoan',
            name='mo_ta_file',
            field=models.CharField(blank=True, help_text='Tài liệu', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filedoan',
            name='dang_ky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_nop', to='QLDA.dangkydoan'),
        ),
        migrations.AlterField(
            model_name='filedoan',
            name='file',
            field=models.FileField(upload_to='bai_nop_do_an/'),
        ),
    ]
