# Generated by Django 5.1 on 2025-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLDA', '0007_filedoan_mo_ta_file_alter_filedoan_dang_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangkydoan',
            name='nhan_xet_gv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
